version: '3'
services:
  centos-8:
    build: configs/centos-8/
    volumes:
      - .:/app
    environment:
      - _NGINX_VERSION
      - _NGINX_RELEASE
  centos-7:
    build: configs/centos-7/
    volumes:
      - .:/app
    environment:
      - _NGINX_VERSION
      - _NGINX_RELEASE
