name: Build CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - release: mainline
            nginx: "1.21.1"
          - release: stable
            nginx: "1.20.1"

    steps:
      - uses: actions/checkout@v2
      - name: Build
        env:
          _NGINX_VERSION: ${{ matrix.nginx }}
        run: make ci
      - name: Check build artifacts
        run: ls -R build/
