name: Build CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - release: mainline
            nginx: "1.21.6"
          - release: stable
            nginx: "1.20.2"

    steps:
      - uses: actions/checkout@v2
      - name: Build
        env:
          _NGINX_VERSION: ${{ matrix.nginx }}
          _NGINX_RELEASE: ${{ matrix.release }}
        run: make ci
      - name: Check build artefacts
        run: ls -R build/
